In [ ]:
!pip install pprint ipywidgets pandas numpy matplotlib sklearn seaborn xgboost scipy yellowbrick statsmodels pandas_profiling

In [1]:
!pip install dask dask_ml

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: dask in /home/andrea/.local/lib/python3.6/site-packages (2.13.0)

# Gusto

Acute myocardial infarction (“heart attack”) is caused by the formation of a clot in oneof the coronary arteries that supply blood to the heart muscle. 

Acute MI is a major public health problem. Mortality is substantial in the period immediately after the event (and also during the years after surviving the initial  infarction). Some patients die before reaching the  hospital. Patients seen in hospitals are reported to have an average mortality within 30 days around 6–15%, with improvement over time. The risk of 30-day mortality strongly depends on various prognostic factors. In younger patients, risks are much lower than in older patients. Other patient demographics are also important (gender, length, weight), as well as the presence of risk factors (hypertension, diabetes, smoking, family history) and the history of previous cardiovascular events (previous MI, angina, stroke, bypass surgery). Relevant presenting characteristics includethe location of the infarction and the extent of ECG abnormalities. Very important is the acute state of the patients reflected by blood pressure,heart rate, and left ventricular function (e.g., presence of shock).

Aim of this study is to find predictors of 30-days mortality.

In [27]:
import warnings
warnings.filterwarnings('ignore')

from ipywidgets import interact, interactive, fixed, interact_manual
import ipywidgets as widgets

from pprint import pprint
from time import sleep

#  load data
import pandas as pd
import numpy as np
import dask.dataframe as dd

import matplotlib
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.linear_model import LogisticRegression, LogisticRegressionCV
from sklearn import metrics
from sklearn.metrics import roc_auc_score
from sklearn.pipeline import Pipeline
from sklearn.decomposition import PCA
from sklearn.base import BaseEstimator

import tpot

import xgboost as xgb

from scipy.special import expit

from yellowbrick.classifier import ConfusionMatrix, ClassBalance, ROCAUC, ClassificationReport, ClassPredictionError

import statsmodels.api as sm
from statsmodels.stats.outliers_influence import variance_inflation_factor

from pandas_profiling import ProfileReport

In [30]:
df = pd.read_csv("./Gusto.csv")
df['eversmk']= (df['smk']!=1).astype(bool)
df['currentsmk']=(df['smk']==3).astype(bool)
# dummify smk categories
for var in ['day30','sho','dia','hyp','hrt','ant','pmi','htn','lip','pan','fam','ttr']:
    df[var]=df[var].astype(bool)
    
df['killip']=df['killip'].astype(int)

df['sexMale']=df['sex'].apply(lambda x: False if x==0 else True)
    
df.drop(['sex',"smk",'a65','st4'], axis=1, inplace=True)
df

,day30,age,killip,sho,dia,hyp,hrt,ant,pmi,hei,wei,htn,lip,pan,fam,ste,ttr,eversmk,currentsmk,sexMale
0,False,70.313,1,False,False,False,False,True,False,177.3,84.0,True,True,False,False,1,True,True,True,False
1,False,59.844,1,False,True,False,False,True,False,172.0,115.0,True,False,False,True,6,False,False,False,False
2,False,59.023,1,False,False,False,True,False,False,170.0,76.0,True,False,False,True,3,False,False,False,False
3,True,80.375,1,False,False,False,True,False,False,154.9,50.0,False,False,False,False,3,False,True,True,True
4,False,64.750,1,False,False,True,False,False,False,167.0,97.4,False,False,True,True,2,True,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3656,False,51.836,1,False,False,False,False,True,False,169.8,65.0,False,False,False,False,7,True,False,False,False
3657,False,51.836,1,False,True,False,False,True,False,167.6,72.1,False,False,True,False,7,True,True,True,False
3658,False,63.977,1,False,False,False,False,False,False,174.2,87.2,True,False,False,False,2,True,True,False,False
3659,False,59.758,1,False,False,False,False,False,False,165.0,57.8,False,False,False,False,6,True,True,True,True
3660,False,52.195,1,False,False,False,False,False,True,180.0,75.0,True,True,False,True,4,True,True,False,False

In [26]:
print(pipeline_optimizer.score(x_test, y_test))

0.9530567685589519

In [ ]:
from yellowbrick.classifier import ROCAUC

rocauc = ROCAUC(exported_pipeline, size=(1080, 720))

rocauc.score(x_test,y_test)  
r = rocauc.poof()